[package]
name = "user_management"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# diesel={version="2.1", features=["postgres"]}
# dotenvy="0.15"

rusqlite={version="0.29.0",features=["bundled"]}



[[bin]]
name = "new"
path = "src/db_management.rs"
test=true
bench=false

